[phases.setup]
nixPkgs = ["python39", "pip", "gcc"]

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "python scheduler_continuous.py"

[variables]
PYTHONUNBUFFERED = "1"

